//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaiUser
    {
        public int idLoaiUser { get; set; }
        public string tenLoaiUser { get; set; }
        public Nullable<System.DateTime> thoiGianPhanQuyen { get; set; }
    }
}
