//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHQTCSDL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectMusicEntities : DbContext
    {
        public ProjectMusicEntities()
            : base("name=ProjectMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaSi> CaSis { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Item> Category_Item { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<loaiUser> loaiUsers { get; set; }
        public virtual DbSet<Lyric> Lyrics { get; set; }
        public virtual DbSet<Music> Musics { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<Playlist_Item> Playlist_Item { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<UserMain> UserMains { get; set; }
        public virtual DbSet<view_getSongFromAdeleSinger> view_getSongFromAdeleSinger { get; set; }
        public virtual DbSet<view_getSongUsukCategoty> view_getSongUsukCategoty { get; set; }
        public virtual DbSet<view_singerAll> view_singerAll { get; set; }
        public virtual DbSet<view_songAll> view_songAll { get; set; }
        public virtual DbSet<view_tacGiaAll> view_tacGiaAll { get; set; }
    
        [DbFunction("ProjectMusicEntities", "TimKiemNhac")]
        public virtual IQueryable<TimKiemNhac_Result> TimKiemNhac(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemNhac_Result>("[ProjectMusicEntities].[TimKiemNhac](@TuKhoa)", tuKhoaParameter);
        }
    
        [DbFunction("ProjectMusicEntities", "TimKiemNhacTheoTenCaSi")]
        public virtual IQueryable<TimKiemNhacTheoTenCaSi_Result> TimKiemNhacTheoTenCaSi(string tenCaSi)
        {
            var tenCaSiParameter = tenCaSi != null ?
                new ObjectParameter("TenCaSi", tenCaSi) :
                new ObjectParameter("TenCaSi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemNhacTheoTenCaSi_Result>("[ProjectMusicEntities].[TimKiemNhacTheoTenCaSi](@TenCaSi)", tenCaSiParameter);
        }
    
        [DbFunction("ProjectMusicEntities", "TimKiemTheLoai")]
        public virtual IQueryable<TimKiemTheLoai_Result> TimKiemTheLoai(string tenTheLoai)
        {
            var tenTheLoaiParameter = tenTheLoai != null ?
                new ObjectParameter("TenTheLoai", tenTheLoai) :
                new ObjectParameter("TenTheLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemTheLoai_Result>("[ProjectMusicEntities].[TimKiemTheLoai](@TenTheLoai)", tenTheLoaiParameter);
        }
    
        public virtual int DeleteMusicById(Nullable<int> idMusic)
        {
            var idMusicParameter = idMusic.HasValue ?
                new ObjectParameter("idMusic", idMusic) :
                new ObjectParameter("idMusic", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMusicById", idMusicParameter);
        }
    
        public virtual ObjectResult<find_song_by_category_Result> find_song_by_category(string category_name)
        {
            var category_nameParameter = category_name != null ?
                new ObjectParameter("category_name", category_name) :
                new ObjectParameter("category_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<find_song_by_category_Result>("find_song_by_category", category_nameParameter);
        }
    
        public virtual ObjectResult<find_song_by_Singer_Result> find_song_by_Singer(string singer_name)
        {
            var singer_nameParameter = singer_name != null ?
                new ObjectParameter("singer_name", singer_name) :
                new ObjectParameter("singer_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<find_song_by_Singer_Result>("find_song_by_Singer", singer_nameParameter);
        }
    
        public virtual int sp_AddMusic(Nullable<int> idCaSi, Nullable<int> idTacGia, Nullable<int> idLyric, string tenBaiHat, string urlBaiHat, string thongTinBaiHat)
        {
            var idCaSiParameter = idCaSi.HasValue ?
                new ObjectParameter("idCaSi", idCaSi) :
                new ObjectParameter("idCaSi", typeof(int));
    
            var idTacGiaParameter = idTacGia.HasValue ?
                new ObjectParameter("idTacGia", idTacGia) :
                new ObjectParameter("idTacGia", typeof(int));
    
            var idLyricParameter = idLyric.HasValue ?
                new ObjectParameter("idLyric", idLyric) :
                new ObjectParameter("idLyric", typeof(int));
    
            var tenBaiHatParameter = tenBaiHat != null ?
                new ObjectParameter("tenBaiHat", tenBaiHat) :
                new ObjectParameter("tenBaiHat", typeof(string));
    
            var urlBaiHatParameter = urlBaiHat != null ?
                new ObjectParameter("urlBaiHat", urlBaiHat) :
                new ObjectParameter("urlBaiHat", typeof(string));
    
            var thongTinBaiHatParameter = thongTinBaiHat != null ?
                new ObjectParameter("thongTinBaiHat", thongTinBaiHat) :
                new ObjectParameter("thongTinBaiHat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddMusic", idCaSiParameter, idTacGiaParameter, idLyricParameter, tenBaiHatParameter, urlBaiHatParameter, thongTinBaiHatParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_deletePlaylist(Nullable<int> idPlaylist)
        {
            var idPlaylistParameter = idPlaylist.HasValue ?
                new ObjectParameter("idPlaylist", idPlaylist) :
                new ObjectParameter("idPlaylist", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletePlaylist", idPlaylistParameter);
        }
    
        public virtual int sp_DeletePlaylistItemById(Nullable<int> idPI)
        {
            var idPIParameter = idPI.HasValue ?
                new ObjectParameter("idPI", idPI) :
                new ObjectParameter("idPI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePlaylistItemById", idPIParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_ThemBaiHatVaoPlaylist(Nullable<int> idPlaylist, Nullable<int> idMusic)
        {
            var idPlaylistParameter = idPlaylist.HasValue ?
                new ObjectParameter("idPlaylist", idPlaylist) :
                new ObjectParameter("idPlaylist", typeof(int));
    
            var idMusicParameter = idMusic.HasValue ?
                new ObjectParameter("idMusic", idMusic) :
                new ObjectParameter("idMusic", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemBaiHatVaoPlaylist", idPlaylistParameter, idMusicParameter);
        }
    
        public virtual int sp_ThemCaSi(Nullable<int> idCaSi, string tenCaSi, string imgCaSi)
        {
            var idCaSiParameter = idCaSi.HasValue ?
                new ObjectParameter("idCaSi", idCaSi) :
                new ObjectParameter("idCaSi", typeof(int));
    
            var tenCaSiParameter = tenCaSi != null ?
                new ObjectParameter("tenCaSi", tenCaSi) :
                new ObjectParameter("tenCaSi", typeof(string));
    
            var imgCaSiParameter = imgCaSi != null ?
                new ObjectParameter("imgCaSi", imgCaSi) :
                new ObjectParameter("imgCaSi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCaSi", idCaSiParameter, tenCaSiParameter, imgCaSiParameter);
        }
    
        public virtual int sp_ThemPlaylist(Nullable<int> idUser, string tenPlaylist, Nullable<System.DateTime> ngayTao)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(int));
    
            var tenPlaylistParameter = tenPlaylist != null ?
                new ObjectParameter("tenPlaylist", tenPlaylist) :
                new ObjectParameter("tenPlaylist", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("ngayTao", ngayTao) :
                new ObjectParameter("ngayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPlaylist", idUserParameter, tenPlaylistParameter, ngayTaoParameter);
        }
    
        public virtual int sp_ThemTacGia(Nullable<int> idTacGia, string tenTacGia)
        {
            var idTacGiaParameter = idTacGia.HasValue ?
                new ObjectParameter("idTacGia", idTacGia) :
                new ObjectParameter("idTacGia", typeof(int));
    
            var tenTacGiaParameter = tenTacGia != null ?
                new ObjectParameter("tenTacGia", tenTacGia) :
                new ObjectParameter("tenTacGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTacGia", idTacGiaParameter, tenTacGiaParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateMusic(Nullable<int> idMusic, Nullable<int> idCaSi, Nullable<int> idTacGia, Nullable<int> idLyric, string tenBaiHat, string urlBaiHat, string thongTinBaiHat)
        {
            var idMusicParameter = idMusic.HasValue ?
                new ObjectParameter("idMusic", idMusic) :
                new ObjectParameter("idMusic", typeof(int));
    
            var idCaSiParameter = idCaSi.HasValue ?
                new ObjectParameter("idCaSi", idCaSi) :
                new ObjectParameter("idCaSi", typeof(int));
    
            var idTacGiaParameter = idTacGia.HasValue ?
                new ObjectParameter("idTacGia", idTacGia) :
                new ObjectParameter("idTacGia", typeof(int));
    
            var idLyricParameter = idLyric.HasValue ?
                new ObjectParameter("idLyric", idLyric) :
                new ObjectParameter("idLyric", typeof(int));
    
            var tenBaiHatParameter = tenBaiHat != null ?
                new ObjectParameter("tenBaiHat", tenBaiHat) :
                new ObjectParameter("tenBaiHat", typeof(string));
    
            var urlBaiHatParameter = urlBaiHat != null ?
                new ObjectParameter("urlBaiHat", urlBaiHat) :
                new ObjectParameter("urlBaiHat", typeof(string));
    
            var thongTinBaiHatParameter = thongTinBaiHat != null ?
                new ObjectParameter("thongTinBaiHat", thongTinBaiHat) :
                new ObjectParameter("thongTinBaiHat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMusic", idMusicParameter, idCaSiParameter, idTacGiaParameter, idLyricParameter, tenBaiHatParameter, urlBaiHatParameter, thongTinBaiHatParameter);
        }
    
        [DbFunction("ProjectMusicEntities", "FUNC_LayDSTheoCategory")]
        public virtual IQueryable<FUNC_LayDSTheoCategory_Result> FUNC_LayDSTheoCategory(Nullable<int> idCategory)
        {
            var idCategoryParameter = idCategory.HasValue ?
                new ObjectParameter("idCategory", idCategory) :
                new ObjectParameter("idCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_LayDSTheoCategory_Result>("[ProjectMusicEntities].[FUNC_LayDSTheoCategory](@idCategory)", idCategoryParameter);
        }
    
        [DbFunction("ProjectMusicEntities", "FUNC_LayDSTheoidPlaylist")]
        public virtual IQueryable<FUNC_LayDSTheoidPlaylist_Result> FUNC_LayDSTheoidPlaylist(Nullable<int> idPlaylist)
        {
            var idPlaylistParameter = idPlaylist.HasValue ?
                new ObjectParameter("idPlaylist", idPlaylist) :
                new ObjectParameter("idPlaylist", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_LayDSTheoidPlaylist_Result>("[ProjectMusicEntities].[FUNC_LayDSTheoidPlaylist](@idPlaylist)", idPlaylistParameter);
        }
    
        public virtual int sp_AddCategory(string nameCategory, Nullable<System.DateTime> ngayTao)
        {
            var nameCategoryParameter = nameCategory != null ?
                new ObjectParameter("nameCategory", nameCategory) :
                new ObjectParameter("nameCategory", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("ngayTao", ngayTao) :
                new ObjectParameter("ngayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddCategory", nameCategoryParameter, ngayTaoParameter);
        }
    
        public virtual int sp_AddMusicToCategory(Nullable<int> idCategory, Nullable<int> idMusic)
        {
            var idCategoryParameter = idCategory.HasValue ?
                new ObjectParameter("idCategory", idCategory) :
                new ObjectParameter("idCategory", typeof(int));
    
            var idMusicParameter = idMusic.HasValue ?
                new ObjectParameter("idMusic", idMusic) :
                new ObjectParameter("idMusic", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddMusicToCategory", idCategoryParameter, idMusicParameter);
        }
    
        public virtual int sp_DeleteCategory(Nullable<int> idCategory)
        {
            var idCategoryParameter = idCategory.HasValue ?
                new ObjectParameter("idCategory", idCategory) :
                new ObjectParameter("idCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteCategory", idCategoryParameter);
        }
    
        public virtual int sp_DeleteMusicfromCategory(Nullable<int> idCategory)
        {
            var idCategoryParameter = idCategory.HasValue ?
                new ObjectParameter("idCategory", idCategory) :
                new ObjectParameter("idCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteMusicfromCategory", idCategoryParameter);
        }
    
        [DbFunction("ProjectMusicEntities", "FUNC_LayDSBHTheoCaSi")]
        public virtual IQueryable<FUNC_LayDSBHTheoCaSi_Result> FUNC_LayDSBHTheoCaSi(Nullable<int> idCaSi)
        {
            var idCaSiParameter = idCaSi.HasValue ?
                new ObjectParameter("idCaSi", idCaSi) :
                new ObjectParameter("idCaSi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUNC_LayDSBHTheoCaSi_Result>("[ProjectMusicEntities].[FUNC_LayDSBHTheoCaSi](@idCaSi)", idCaSiParameter);
        }
    }
}
