//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.Category_Item = new HashSet<Category_Item>();
            this.Comments = new HashSet<Comment>();
            this.Playlist_Item = new HashSet<Playlist_Item>();
        }
    
        public int idMusic { get; set; }
        public Nullable<int> idCaSi { get; set; }
        public Nullable<int> idtacGia { get; set; }
        public Nullable<int> idLyric { get; set; }
        public string tenBaiHat { get; set; }
        public string urlBaiHat { get; set; }
        public string thongTinBaiHat { get; set; }
        public string imgMusic { get; set; }
    
        public virtual CaSi CaSi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Item> Category_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Lyric Lyric { get; set; }
        public virtual TacGia TacGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist_Item> Playlist_Item { get; set; }
    }
}
