//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_getSongUsukCategoty
    {
        public int idMusic { get; set; }
        public Nullable<int> idCaSi { get; set; }
        public Nullable<int> idtacGia { get; set; }
        public Nullable<int> idLyric { get; set; }
        public string tenBaiHat { get; set; }
        public string urlBaiHat { get; set; }
        public string thongTinBaiHat { get; set; }
    }
}
