//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_singerAll
    {
        public int idCaSi { get; set; }
        public string tenCaSi { get; set; }
    }
}
